<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DirioSemanalMensalAnualData baseTotal d_f7f0c0</name>
   <tag></tag>
   <elementGuidId>e084989f-55c9-4418-9947-b7950f832810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dashboard-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/main/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;DiárioSemanalMensalAnualData base:Total de veículos: 0Total de ligeiros: 0Total &quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5af330d-7c26-42ab-a2de-567b9d10074d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboard-container</value>
      <webElementGuid>4957ca4f-e53d-4ea5-9ade-bfd5c55f4d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DiárioSemanalMensalAnualData base:Total de veículos: 0Total de ligeiros: 0Total de motas: 0Total de camiões: 0Total de autocarros: 0Total de bicicletas: 0Mais movimentada: N/AMenos movimentada: N/AVeículos em excesso: 11Hora com mais tráfego: 18-19Hora com menos tráfego: 02-03Comparação com há 7 dias: +2%Localizações existentesSem localizações disponíveis.Nenhum gráfico selecionado.Atualizado em: </value>
      <webElementGuid>2ff9a61e-5521-41d6-b43a-bf6465ff8b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-container&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;dashboard-container&quot;]</value>
      <webElementGuid>868c022c-c4be-446b-abfd-4cec283293d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/main/div</value>
      <webElementGuid>6b05bab4-c3b2-4d8c-b60f-4a9f29030bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::div[1]</value>
      <webElementGuid>d88f93ee-6d0c-4f9f-b2af-dc426be799b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[1]</value>
      <webElementGuid>e423980f-e899-49b6-8140-c45729d7e8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>0a208a96-6cbd-42e6-9bef-b27971aa0d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DiárioSemanalMensalAnualData base:Total de veículos: 0Total de ligeiros: 0Total de motas: 0Total de camiões: 0Total de autocarros: 0Total de bicicletas: 0Mais movimentada: N/AMenos movimentada: N/AVeículos em excesso: 11Hora com mais tráfego: 18-19Hora com menos tráfego: 02-03Comparação com há 7 dias: +2%Localizações existentesSem localizações disponíveis.Nenhum gráfico selecionado.Atualizado em: ' or . = 'DiárioSemanalMensalAnualData base:Total de veículos: 0Total de ligeiros: 0Total de motas: 0Total de camiões: 0Total de autocarros: 0Total de bicicletas: 0Mais movimentada: N/AMenos movimentada: N/AVeículos em excesso: 11Hora com mais tráfego: 18-19Hora com menos tráfego: 02-03Comparação com há 7 dias: +2%Localizações existentesSem localizações disponíveis.Nenhum gráfico selecionado.Atualizado em: ')]</value>
      <webElementGuid>4e3ccf06-83de-4c8b-9787-c8435524fbcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
