<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Noroeste_icon</name>
   <tag></tag>
   <elementGuidId>e64cc2fa-4ad0-45b1-98cb-7f305b3723cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td.action-buttons > button:nth-of-type(3) > img.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/main/div/div/div/table/tbody/tr[4]/td[4]/button[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;trash&quot;i] >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ec98933-3abb-4a68-aef1-ad9c85d18f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/src/components/icons/trash.svg</value>
      <webElementGuid>2da64ced-42a6-4cb9-acdc-374d18171194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>trash</value>
      <webElementGuid>0205bf4e-35f4-4d8a-ac78-2370d8681304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>a09cb7f0-e256-4298-bcec-aff929a4fcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-container&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;flex flex-col items-center&quot;]/div[@class=&quot;locations-column&quot;]/div[@class=&quot;locations-table&quot;]/table[1]/tbody[1]/tr[4]/td[@class=&quot;action-buttons&quot;]/button[3]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>d1f41db5-15a3-4340-965a-d7106d4816ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/main/div/div/div/table/tbody/tr[4]/td[4]/button[3]/img</value>
      <webElementGuid>72ee5525-326a-4c4b-9a4b-b55a529cd313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='trash'])[4]</value>
      <webElementGuid>709adc27-0e0e-4388-8015-1d7ae7cb3bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/button[3]/img</value>
      <webElementGuid>4b62d1cd-2aae-4314-9718-badda0992392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/src/components/icons/trash.svg' and @alt = 'trash']</value>
      <webElementGuid>20e959cc-ba9a-4466-a494-e916034038eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
