<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Menos movimentada Rua XPTOOO</name>
   <tag></tag>
   <elementGuidId>c7f7f6e1-6fc7-407c-bb15-8da937495a96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/main/div/div/div/div[3]/div[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Menos movimentada: Rua XPTOOO&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>683ac823-762c-4f0d-bb2a-8c489295beff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stat-card</value>
      <webElementGuid>44c6a76e-2617-488e-a3fb-935bf156d0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menos movimentada: Rua XPTOOO</value>
      <webElementGuid>1b1acc1a-723f-49f3-b0a1-8056d36800c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-container&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;dashboard-container&quot;]/div[@class=&quot;top-section&quot;]/div[@class=&quot;summary-column&quot;]/div[@class=&quot;stats-grid&quot;]/div[@class=&quot;stat-card&quot;]</value>
      <webElementGuid>e93bdf46-6276-4d9f-9826-a05b930b0437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/main/div/div/div/div[3]/div[8]</value>
      <webElementGuid>efd23b07-26da-4a4b-a1d9-0e73246a1737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais movimentada: Rua teste23'])[1]/following::div[1]</value>
      <webElementGuid>7928c675-2ea5-46d9-a1be-3659920283e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total de bicicletas: 0'])[1]/following::div[2]</value>
      <webElementGuid>1de1aab3-3976-410b-8bab-f522fa0897c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veículos em excesso: 11'])[1]/preceding::div[1]</value>
      <webElementGuid>a82e4598-9662-494f-bcea-3c5def3a1461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hora com mais tráfego: 18-19'])[1]/preceding::div[2]</value>
      <webElementGuid>a1e57147-a99a-4d2f-bcf3-878be31968f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menos movimentada: Rua XPTOOO']/parent::*</value>
      <webElementGuid>d5a88b7a-3440-4276-ad21-6b92b88ef881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>fa408277-1031-44fd-a5d8-0fa5e7d4bb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Menos movimentada: Rua XPTOOO' or . = 'Menos movimentada: Rua XPTOOO')]</value>
      <webElementGuid>2d2189e8-51b6-40d1-a8f0-86a0ce5ba396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
