<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_Dashboard  Localizaes  Configurao  Logi_26041a</name>
   <tag></tag>
   <elementGuidId>77fb3a59-e924-476e-8abb-0523d5792de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.navbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Dashboard Localizações Configuração Login Logout&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>1f591f7d-dd30-4527-821f-e9ae718e4fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar</value>
      <webElementGuid>9ee7a775-efbf-43ae-bce8-240cf85ca29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dashboard  Localizações  Configuração  Login  Logout </value>
      <webElementGuid>817ac23c-9b96-477e-be92-c27742a740e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-container&quot;]/nav[@class=&quot;navbar&quot;]</value>
      <webElementGuid>4539147d-1ae9-4cde-b486-ded7521a3392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/nav</value>
      <webElementGuid>97484e81-2cef-4164-86e8-e5b233ce658a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav</value>
      <webElementGuid>3291e970-f5ad-45b5-ae6f-0b0fad3277e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = ' Dashboard  Localizações  Configuração  Login  Logout ' or . = ' Dashboard  Localizações  Configuração  Login  Logout ')]</value>
      <webElementGuid>6ea99b33-c999-4af2-b259-a9a8dd36268f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
