<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sucesso</name>
   <tag></tag>
   <elementGuidId>aa7c820b-229f-4537-aba7-636f28b51238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-sm.font-semibold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='2']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sucesso&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6c39318-a8bc-499e-a933-fdafcb7e78d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-semibold</value>
      <webElementGuid>e80f9f99-58cd-4727-9ead-41162b60bcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sucesso</value>
      <webElementGuid>68498923-493a-4df1-8ab7-8d8cc0da6730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)/div[@class=&quot;grid gap-1&quot;]/div[@class=&quot;text-sm font-semibold&quot;]</value>
      <webElementGuid>f01edf92-5d29-4edb-b7ea-2c6dcf30d678</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='2']/div/div</value>
      <webElementGuid>3e3a6f6d-7884-4358-b60d-1ce4fa6aba9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::div[2]</value>
      <webElementGuid>f78a661f-a548-4c42-ac3f-40879bda66e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sucesso']/parent::*</value>
      <webElementGuid>a26be38b-2601-451e-af99-fc826724777c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>52edb5c2-3bb9-4c8d-a050-6831ee13c3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sucesso' or . = 'Sucesso')]</value>
      <webElementGuid>64dfd2b3-fa1a-4aac-ab94-c14792b04bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
