<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sul_icon</name>
   <tag></tag>
   <elementGuidId>9f2fd672-e3ba-47ee-b226-72528f980a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.action-buttons > button > img.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/main/div/div/div/table/tbody/tr[2]/td[4]/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;eye&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>95c1c717-0129-4af6-9db8-4b95e3c9236e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/src/components/icons/eye.svg</value>
      <webElementGuid>224a8c39-eda7-4d93-91c7-0ecf49ed6d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>eye</value>
      <webElementGuid>1fc3ed33-7050-4650-ac38-f276cb4c3ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>22962bc9-1770-4756-9150-bd31b1a595aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-container&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;flex flex-col items-center&quot;]/div[@class=&quot;locations-column&quot;]/div[@class=&quot;locations-table&quot;]/table[1]/tbody[1]/tr[2]/td[@class=&quot;action-buttons&quot;]/button[1]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>a6df4e74-11b5-4dee-91b6-79f9fb28fc07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/main/div/div/div/table/tbody/tr[2]/td[4]/button/img</value>
      <webElementGuid>6d61c1ec-b97e-453d-b397-f1ec6840bfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='eye'])[2]</value>
      <webElementGuid>2574653a-22ec-4ed9-9e0c-35d6068f3f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/button/img</value>
      <webElementGuid>dc03874c-3700-4495-bebf-9110c8f44b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/src/components/icons/eye.svg' and @alt = 'eye']</value>
      <webElementGuid>794fe42e-3a0b-4593-8055-8cbbca095060</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
